
#source 'https://github.com/screenmeet/screenmeet-live-sdk-ios.git'
 
target 'ScreenMeet' do
  	# Comment the next line if you don't want to use dynamic frameworks
  	use_frameworks!

 	pod ScreenMeet
end
